### ISSUE TITLE
There are many slight variations of the survey data across the DC repo.

### ISSUE THREAD

**Issue by lwasser** [lwasser/python-ecology#16]
We should either use the figshare download always OR make sure what we store is current. the data in this repo had a few modifications. For instance the species_id field was renamed "species" to demonstrate the point that the column headers need to be considered when working with spreadsheets.

**Comment by fmichonneau** [comment]
+1 to use the dataset from figshare. It's cleaner, more consistent (similar
headers across datasets) and that's what the other lessons are using.

**Comment by lwasser** [comment]
Thanks @fmichonneau . i'm closing this given Ethan started an issue in the DC planning repo. He is open to adding a "messy version" of the data for us to explicitly use in the lessons to maintain some consistency.

https://github.com/datacarpentry/planning/issues/3
