### ISSUE TITLE
Python setup instructions for workshop

### ISSUE THREAD

**Issue by lwasser** [lwasser/python-ecology#6]
Installing pandas was embedded in an activity. I'm thinking we have them install pandas prior to the workshop. Are there instructions somewhere for that to include with the workshop page?

Also how can we test whether
1. anaconda is installed
2. the right packages are installed to: Pandas, matplotlib and OS

**Comment by qjcg** [comment]
For our upcoming workshop, we have requested that participants install Anaconda in our setup instructions.

In terms of validating a participant's installation, we could instruct participants to run the SWC installation test scripts:

https://github.com/swcarpentry/workshop-template/blob/gh-pages/setup/index.md

(Making sure that unneeded packages are duly commented out in the CHECKS list in swc-installation-test-2.py by an instructor in advance.)

**Comment by lwasser** [comment]
cool thanks. can you please shoot me a link to your repo?

leah

**Comment by qjcg** [comment]
Sure! The main repo for next week's DC workshop is:

https://github.com/fmichonneau/2015-03-30-umiami

**Comment by tracykteal** [comment]
Thanks @qjcg This does include all the install instructions, and we've been using the SWC installer too. https://github.com/swcarpentry/windows-installer

**Comment by lwasser** [comment]
Ok wonderful. So should we merge that SWC materials into this repo? What we could potentially do it setup the YAML so that the language could be specified and if it's python, it includes the python setup instructions on the landing page for the workshop. Just a thought.

**Comment by tracykteal** [comment]
Having a setup YAML for automatic inclusion of the correct setup instructions on the landing page is a great idea. Do you happen to have an example of something like that implemented anywhere?

**Comment by lwasser** [comment]
hey tracy -- sure it's super easy to implement and i can create and example page if you want
It's just a conditional statement. 

here is a page:
 http://neondataskills.org/HDF5/Create-Raster-Stack-Spectroscopy-HDF5-In-R/

this page layout has one at the very bottom called related code.  This block appears if i specify one or more files in the YAML. For DC, it could just look to see what language is in the yaml so {{ if page.language == 'Python' }} or whatever then include R-setup.html else include Python-setup.html. Or something like that . We'd then add a language tag to the YAML and folks would just fill it out.
Here's the related code block that the page uses:
https://github.com/lwasser/NEON-Data-Skills/blob/gh-pages/_includes/_relatedCode.html
Here is an example of a jekyll if statement.:
{% if page.code1%}

<div id="relatedCode">
<h2>GET RELATED CODE</h2>
Right Click to download associated code:
<ul>
<li>
<a href="{{ site.baseurl }}/code/{{ page.code1 }}" class="btn btn-info"> {{ page.code1 }} </a> </li>{% endif %}
{% if page.code2%} <li><a href="{{ site.baseurl }}/code/{{ page.code2 }}">{{ page.code2 }} </a></li>{% endif %}
</ul>
</div>

The post page calls the include file:
https://github.com/lwasser/NEON-Data-Skills/blob/gh-pages/_layouts/post.html
 For DC it would make more sense to just have the conditional statment on the post.html layout page. then include whatever setup page is required.

 {{ if page.language == 'Python' }}
 {% include Python-Setup.html %}

{{else }}
{% include R-Setup.html %}
{{ endif }}

i could make an example for you if you'd like with the python page. it sounds like ethan would like us to discuss the gh-pages implementation of DC materials over the list serve.

**Comment by lwasser** [comment]
@tracykteal 

http://lwasser.github.io/2015-04-15-SEA-UCAR/ 

the index.html page has this implemented for you to see.
